spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

razorpay.key=rzp_live_SfKMrx46boiwWf
razorpay.secret=8CApbat0UvpMMkT5W6runVrS

admin.username=Rabbani
admin.password=Rabbani123

